spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev   #开发环境
  application:
    name: microserviceclouddemo-config-atgugui-dev

---
spring:
  profiles: test    #测试环境
  application:
    name: microserviceclouddemo-config-atgugui-test

#请保存为utf-8格式